services:
  test:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: pytest --color=yes --code-highlight=yes
    networks:
      minichris:
    userns_mode: host
    user: root
    working_dir: /app
    volumes:
      - "wd:/app:rw"
      - "./src/chrisomatic:/app/chrisomatic:ro"
      - "./tests:/app/tests:ro"
      - "./scripts:/app/scripts:ro"
      - "./pytest.ini:/app/pytest.ini:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"

networks:
  minichris:
    external: true
    name: minichris-local

volumes:
  wd:
