[tool.poetry]
name = "chrisomatic"
version = "0.1.1"
description = "Setup ChRIS with plugins and powerpointlessnes."
authors = ["Jennings Zhang <jenni_zh@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.4.0"
aiohttp = "^3.8.1"
rich = "^11.2.0"
pyserde = "^0.7.0"
aiodocker = "^0.21.0"
strictyaml = "^1.6.1"

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.18.1"
black = "^22.1.0"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
chrisomatic = "chrisomatic.cli.typer:app"

[tool.pytest.ini_options]
asyncio_mode = "auto"
