[tool.poetry]
name = "chrisomatic"
version = "0.3.1"
description = "ChRIS backend provisioner with Powerpointlessness"
authors = ["Jennings Zhang <Jennings.Zhang@childrens.harvard.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.6.1"
aiohttp = "^3.8.1"
rich = "^12.5.1"
pyserde = "^0.8.3"
aiodocker = "^0.21.0"
strictyaml = "^1.6.1"

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.18.1"
black = "^22.1.0"
pre-commit = "^2.17.0"
prospector = "^1.7.7"
mypy = "^0.971"
bandit = "^1.7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
chrisomatic = "chrisomatic.cli.typer:app"

[tool.pytest.ini_options]
asyncio_mode = "auto"
