version: "3.8"

services:
  dev:
    build:
      context: ..
      dockerfile: testing_harness/Dockerfile
    command: pytest --color=yes --code-highlight=yes -o cache_dir=/var/cache/pytest
    networks:
      minichris:
    userns_mode: host
    user: root
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "../:/usr/local/src/chrisomatic:ro"
      - "pytest-cache:/var/cache/pytest:rw"
      - "./scripts:/t:ro"
#    depends_on:
#      - volume-permissions-fix
#
#  volume-permissions-fix:
#    image: alpine
#    command: chmod 777 /var/cache/pytest
#    volumes:
#      - "pytest-cache:/var/cache/pytest:rw"


networks:
  minichris:
    external: true
    name: minichris-docker_local

volumes:
  pytest-cache:
