version: "3.8"

services:
  dev:
    build:
      context: ..
      dockerfile: testing_harness/Dockerfile
    networks:
      minichris:
    userns_mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "../:/usr/local/src/chrisomatic:ro"
      - "pytest-cache:/var/cache/pytest:rw"
      - "./scripts:/t:ro"

networks:
  minichris:
    external: true
    name: minichris_local

volumes:
  pytest-cache:
