= `chrisomatic` Schema Interpretation

This document describes how `chrisomatic` interprets a configuration file.

== General Behavior

`chrisomatic` operates _additively_, meaning that it will only create
data.

== Default Resolution

The schema is flexible and uses defaults where values are not specified.

=== Compute Environments

If xref:schema.adoc#plugins_compute_resource[`compute_resource`]
is not given for a
xref:schema.adoc#cube_plugins[`cube.plugin`], by default it
will be registered to all known compute environments in
xref:schema.adoc#cube_compute_resource[`cube.compute_resource`].

[source,yaml]
----
on:
  cube_url: http://localhost:8000/api/v1/
  chris_store_url: http://localhost:8010/api/v1/
  chris_superuser:
    username: chris
    password: chris1234

chris_store:
  users:
    - username: jennings
      password: abetterpassword
    - username: gideon
      password: gideonstrumpet

cube:
  compute_resource:
    - name: moc
      url: https://example.com/api/v1/
      username: fake
      password: fake1234
      description: Mass Open Cloud
    - name: hpc
      url: https://example.com/api/v1/
      username: fake
      password: fake1234
      description: High-performance computing cluster

  plugins:
    - name: pl-in-development
      dock_image: "localhost:5000/fnndsc/pl-indevelopment:latest"
----

In the example above, the plugin `pl-in-development` will be registered
to all specified compute environments, `moc` and `hpc`.


[#plugin_string_resolution]
=== Plugin String Resolution

If a xref:schema.adoc#cube_plugins[plugin] is a string,
it will be resolved by this procedure:

First, if _plugin_ is a container image present in the host's docker daemon,
_plugin_ is interpreted as xref:schema.adoc#plugin_dock_image[`dock_image`].

Else, _plugin_ will be interpreted based on patterns, matching as
these fields in this order:

1. xref:schema.adoc#plugin_url[_ChRIS_ store plugin URL], e.g. `https://chrisstore.co/api/v1/plugins/45/`
2. xref:schema.adoc#plugin_dock_image[`dock_image`], e.g. `docker.io/fnndsc/pl-simpledsapp:1.2.3`
3. xref:schema.adoc#plugin_public_repo[`public_repo`], e.g. `https://github.com/FNNDSC/pl-simpledsapp`
4. xref:schema.adoc#plugin_name[plugin name], e.g. `pl-simpledsapp`


[#plugin_registration_strategy]
=== Plugin Registration Strategy

If a xref:schema.adoc#cube_plugins[Plugin] is not registered to
its xref:schema.adoc#plugins_compute_resource[compute environments],
`chrisomatic` will attempt to do the following:

1. Search for the _plugin_ in the
   xref:schema.adoc#chris_store_url[linked _ChRIS_ store].
2. Search for the _plugin_ in
   xref:schema.adoc#public_store[the list of public _ChRIS_ store instances],
   in the specified order. (default: `["https://chrisstore.co/api/v1/"]`)
3. Attempt to upload the _plugin_ to the
   xref:schema.adoc#chris_store_url[linked _ChRIS_ store].

Searching public _ChRIS_ store instances can be disabled (i.e. force upload to local store):

[source,yaml]
----
on:
  cube_url: http://localhost:8000/api/v1/
  chris_store_url: http://localhost:8010/api/v1/
  chris_superuser:
    username: chris
    password: chris1234
  public_store: []
----

[#plugin_representation_strategy]
=== Plugin JSON Description Strategy

Most _ChRIS_ plugins are created from either
https://github.com/FNNDSC/cookiecutter-chrisapp[cookiecutter-chrisapp],
or can be described by the
https://pypi.org/project/chris-plugin/[`chris_plugin_info`] tool.

`chrisomatic` will try to produce the plugin JSON representation
by executing the _plugin_'s
xref:plugin_dock_image[`dock_image`] as a container. It will try
these commands, and if one doesn't work, it tries the next:

1. `chris_plugin_info`
2. `{{CMD}} --json`, where `{{CMD}}` is the `CMD` set by `Dockerfile`
