= _ChRIS_ Configuration YAML Spec
Jennings <Jennings.Zhang@childrens.harvard.edu>
:version: 1.1
:toc:

A _ChRIS_ configuration file is a https://yaml.org/[YAML] file which describes the state of a _ChRIS_ system.

== File Specification

Not all fields are required. Most of them can be guessed or inferred.

=== version

Type: Literal[1.1]

=== on

Information about the _ChRIS_ system.

==== on.cube_url

Type: string

URL of _ChRIS_ backend.

==== on.chris_superuser

Type: <<User>>

Admin user of _ChRIS_ backend, i.e.
user who is able to register plugins to _ChRIS_.

[#public_store]
==== on.public_store

Type: list[string]

Default: [https://cube.chrisproject.org/api/v1/]

Specify public instance(s) of _ChRIS_ stores from where to
get plugins from.

=== cube

_ChRIS_ backend description.

[#cube-users]
==== cube.users

Type: list[<<User>>]

[#cube_compute_resource]
==== cube.compute_resource

Type: list[<<ComputeResource,ComputeResource>>]

[#ComputeResource]
===== cube.compute_resource[*] (ComputeResource)

[#compute_resource_name]
====== cube.compute_resource[*].name

Type: string

====== cube.compute_resource[*].url

Type: string

====== cube.compute_resource[*].username

Type: string

====== cube.compute_resource[*].password

Type: string

====== cube.compute_resource[*].description

Type: string

[#cube_plugins]
==== cube.plugins

Type: list[string | Plugin]

If value is a string, then it may represent any of: <<plugin_url,peer CUBE plugin url>>, <<plugin_name,plugin name>>,
<<plugin_dock_image,image tag>>,
<<plugin_public_repo,code repository URL>>.

[#plugin_url]
===== cube.plugins[*].url

Type: str

A peer CUBE plugin URL, e.g. `https://cube.chrisproject.org/api/v1/plugins/99/`

[#plugin_name]
===== cube.plugins[*].name

Type: str

Name of a plugin in a peer CUBE, e.g. `pl-dircopy`

===== cube.plugins[*].version

Type: str

Version of plugin, e.g. `1.0.0`

[#plugin_dock_image]
===== cube.plugins[*].dock_image

Type: str

Container image manifest, e.g. `docker.io/fnndsc/pl-dircopy:latest`

[#plugin_public_repo]
===== cube.plugins[*].public_repo

Type: str

URL of a source code repository, e.g. `https://github.com/FNNDSC/pl-dircopy`

[#plugins_compute_resource]
===== cube.plugins[*].compute_resource

Type: list[str]

Names of which compute environments to register this plugin to.

If unspecified, use <<cube_compute_resource,cube.compute_resource[0]>>.

==== cube.pipelines

Type: list[string | <<pipelines,Pipeline>>]

[#pipelines]
===== cube.pipelines[*] (Pipeline)

If an element of `cube.pipelines` is a string, then it is interpreted as a
<<PipelineSource,PipelineSource>>.

[#PipelineSource]
====== cube.pipelines[*].src (PipelineSource)

A `PipelineSource` is one of:

- A _ChRIS_ store pipeline, e.g. `https://cube.chrisproject.org/api/v1/pipelines/1/`
- A URI (starting with `http://`, `https://`, `ipfs://`, ...) of a JSON pipeline description.
- A path on the local filesystem to a JSON pipeline description.

The JSON pipeline description may specify its `plugin_tree` as either a
serialized string or an object.

====== cube.pipelines[*].owner

Type: str

Username of _ChRIS_ user defined in <<cube-users>> which owns this pipeline.
If not specified, then the default is `cube.users[0]`.

== Common Types

=== User

An object `{username: string, password: string}`
